/*
 * Generated by MTK SP DrvGen Version: 3.5.160809 for MT6893.
 * 2026-07-24 17:45:31
 * Do Not Modify The File.
 * Copyright Mediatek Inc. (c) 2016.
*/

#ifndef __CUST_POWER_H
#define __CUST_POWER_H



#endif /* __CUST_POWER_H */
